import { useState, useEffect } from 'react';
import { generateEvacuationBriefing } from '../../lib/gemini';

export default function AIRouteAdvisor({ activeIncidents }) {
  const [briefing, setBriefing] = useState(null);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (!activeIncidents || activeIncidents.length === 0) {
      return;
    }

    const regenerateBriefing = async () => {
      setLoading(true);
      try {
        const result = await generateEvacuationBriefing(activeIncidents);
        setBriefing(result);
      } catch (e) {
        console.error('Failed to generate briefing:', e);
      }
      setLoading(false);
    };

    regenerateBriefing();
  }, [activeIncidents]);

  const handleRegenerate = async () => {
    setLoading(true);
    try {
      const result = await generateEvacuationBriefing(activeIncidents);
      setBriefing(result);
    } catch (e) {
      console.error('Failed to regenerate briefing:', e);
    }
    setLoading(false);
  };

  if (!activeIncidents || activeIncidents.length === 0) {
    return null;
  }

  return (
    <div className="panel-card" style={{ marginTop: 20 }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 }}>
        <div>
          <h3 className="t-title">🤖 AI Route Advisor</h3>
          <p className="t-caption" style={{ margin: '4px 0 0', color: 'var(--color-tertiary)' }}>Generated by Gemini AI</p>
        </div>
        <button className="btn-tonal" onClick={handleRegenerate} disabled={loading} style={{ minWidth: 140 }}>
          {loading ? 'Regenerating...' : 'Regenerate'}
        </button>
      </div>

      {briefing && (
        <div>
          <div style={{ background: 'var(--color-surface-container-low)', padding: 16, borderRadius: 12, marginBottom: 12 }}>
            <p className="t-label" style={{ margin: '0 0 10px' }}>Evacuation Briefing</p>
            <ul style={{ margin: 0, paddingLeft: 20 }}>
              {briefing.briefing.map((point, i) => (
                <li key={i} className="t-body-sm" style={{ marginBottom: 8 }}>
                  {point}
                </li>
              ))}
            </ul>
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>
            <div className="info-callout" style={{ padding: 12 }}>
              <p className="t-label" style={{ margin: 0 }}>Zones to Avoid</p>
              <p className="t-body-sm" style={{ margin: '6px 0 0' }}>{briefing.zonesAvoid}</p>
            </div>
            <div className="info-callout" style={{ padding: 12 }}>
              <p className="t-label" style={{ margin: 0 }}>Exits Recommended</p>
              <p className="t-body-sm" style={{ margin: '6px 0 0' }}>{briefing.exitsRecommended}</p>
            </div>
          </div>

          {briefing.specialInstructions && (
            <div className="info-callout" style={{ padding: 12, marginTop: 12 }}>
              <p className="t-label" style={{ margin: 0 }}>Special Instructions</p>
              <p className="t-body-sm" style={{ margin: '6px 0 0' }}>{briefing.specialInstructions}</p>
            </div>
          )}
        </div>
      )}

      {loading && !briefing && (
        <div style={{ textAlign: 'center', padding: 20 }}>
          <p className="t-body-sm">Generating evacuation briefing...</p>
        </div>
      )}
    </div>
  );
}
